# Generated by ChatGPT
# Use an OpenJDK base image
FROM eclipse-temurin:23-jdk

# Set working directory inside the container
WORKDIR /app

# Copy the built JAR into the container
COPY target/tea-shop-1.0-SNAPSHOT.jar ./tea-shop-1.0-SNAPSHOT.jar

# Run the app
ENTRYPOINT ["java", "-jar", "tea-shop-1.0-SNAPSHOT.jar"]